services:
  - type: web
    name: saransh-ai
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python -m nltk.downloader punkt stopwords
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --max-requests 100 --max-requests-jitter 10
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
      - key: PORT
        value: 10000
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONGC
        value: 1
      - key: MPLCONFIGDIR
        value: /tmp/matplotlib
      - key: TORCH_HOME
        value: /tmp/torch
      - key: HF_HOME
        value: /tmp/huggingface 